# Generated by Django 4.1.2 on 2022-10-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yarik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_id', models.TextField(blank=True, null=True, verbose_name='aircraft id')),
                ('engine_position', models.TextField(blank=True, null=True, verbose_name='engine position')),
                ('n1_modifier', models.TextField(blank=True, null=True, verbose_name='n1 modifier')),
                ('number_blades', models.TextField(blank=True, null=True, verbose_name='number blades')),
                ('engine_family', models.TextField(blank=True, null=True, verbose_name='engine family')),
                ('engine_type', models.TextField(blank=True, null=True, verbose_name='engine type')),
                ('manufacturer', models.TextField(blank=True, null=True, verbose_name='manufacturer')),
                ('ZHPTAC', models.TextField(blank=True, null=True, verbose_name='HPT ACTIVE CLEARANCE CNTL')),
                ('ZLPTAC', models.TextField(blank=True, null=True, verbose_name='LPT ACTIVE CLEARANCE CNTL')),
                ('ZPCN12', models.TextField(blank=True, null=True, verbose_name='N1 INDICATED')),
                ('ZPCN25', models.TextField(blank=True, null=True, verbose_name='N2 (HIGH SPEED ROTOR)')),
                ('ZPHSF', models.TextField(blank=True, null=True, verbose_name='PHASE ANGLE')),
                ('ZPHSR', models.TextField(blank=True, null=True, verbose_name='PHASE ANGLE (REAR)')),
                ('ZPN12R', models.TextField(blank=True, null=True, verbose_name='CORRECTED N1 INPUT FROM FADEC (%RPM)')),
                ('ZPOIL', models.TextField(blank=True, null=True, verbose_name='OIL PRESSURE (PSI)')),
                ('ZPS3', models.TextField(blank=True, null=True, verbose_name='PS13 (FAN OGV DISCHARGE)')),
                ('ZT1AB', models.TextField(blank=True, null=True, verbose_name='TOTAL AIR TEMP (DEG C)')),
                ('ZT3', models.TextField(blank=True, null=True, verbose_name='HPC DISCHARG TOT TEMP (DEG)')),
                ('ZT49', models.TextField(blank=True, null=True, verbose_name='EGT-HPT DISCHRG TOT TMP(DEG)')),
                ('ZTAMB', models.TextField(blank=True, null=True, verbose_name='STATIC AIR TEMPERATURE FROM FADEC (DEG R)')),
                ('ZTLA', models.TextField(blank=True, null=True, verbose_name='THROTTLE LEVER ANGLE(DEG)')),
                ('ZTNAC', models.TextField(blank=True, null=True, verbose_name='NACELLE TEMP(DEG C)')),
                ('ZTOIL', models.TextField(blank=True, null=True, verbose_name='OIL TEMP (DEG C)')),
                ('ZVB1F', models.TextField(blank=True, null=True, verbose_name='VIB FAN/LO SPD (FAN PICKUP)')),
                ('ZVB1R', models.TextField(blank=True, null=True, verbose_name='VIB LPT/LOW SPD(REAR PICKUP)')),
                ('ZVB2F', models.TextField(blank=True, null=True, verbose_name='VIB COR/HI SPD (FAN PICKUP)')),
                ('ZVB2R', models.TextField(blank=True, null=True, verbose_name='VIB HPT/HI SPD (REAR PICKUP)')),
                ('ZVSV', models.TextField(blank=True, null=True, verbose_name='INDICATED_AIR_SPEED')),
                ('ZWF36', models.TextField(blank=True, null=True, verbose_name='VAR STATOR VANES POS (VAR)')),
                ('IHPSOV', models.TextField(blank=True, null=True, verbose_name='PACK FLOW 1')),
                ('aircraft_family', models.TextField(blank=True, null=True, verbose_name='aircraft family')),
                ('aircraft_type', models.TextField(blank=True, null=True, verbose_name='aircraft type')),
                ('aircraft_grp', models.TextField(blank=True, null=True, verbose_name='aircraft grp')),
                ('ac_manufacturer', models.TextField(blank=True, null=True, verbose_name='ac manufacturer')),
                ('AGW', models.TextField(blank=True, null=True, verbose_name='ACTUAL GROSS WEIGHT (LB)')),
                ('CAS', models.TextField(blank=True, null=True, verbose_name='COMPUTED AIR SPEED (KNOTS)')),
                ('IAI', models.TextField(blank=True, null=True, verbose_name='WING A/I')),
                ('IVS12', models.TextField(blank=True, null=True, verbose_name='ISOLATION VALVE SWITCH 1-2')),
                ('SAT', models.TextField(blank=True, null=True, verbose_name='STATIC AIR TEMPERATURE (SAT)')),
                ('ZALT', models.TextField(blank=True, null=True, verbose_name='PRESSURE ALTITUDE (FEET)')),
                ('ZT1A', models.TextField(blank=True, null=True, verbose_name='TOTAL AIR TEMP (DEG C)')),
                ('ZVIAS', models.TextField(blank=True, null=True, verbose_name='INDICATED_AIR_SPEED')),
                ('ZWBP1', models.TextField(blank=True, null=True, verbose_name='PACK FLOW 1')),
                ('ZWBP1_8E', models.TextField(blank=True, null=True, verbose_name='CF34-8E PACK FLOW 1 - NOT USED BY BLEED ADJUSTMENT')),
                ('ZWBP2', models.TextField(blank=True, null=True, verbose_name='PACK FLOW 2')),
                ('ZWBP2_8E', models.TextField(blank=True, null=True, verbose_name='CF34-8E PACK FLOW 2 - NOT USED BY BLEED ADJUSTMENT')),
                ('ZXM', models.TextField(blank=True, null=True, verbose_name='MACH')),
                ('IBE', models.TextField(blank=True, null=True, verbose_name='ENG BLEED VALVE ENG 1')),
                ('IBP', models.TextField(blank=True, null=True, verbose_name='PACK VALVE 1')),
                ('IAIE', models.TextField(blank=True, null=True, verbose_name='ENG ANTI-ICE SETTING')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Все данные',
                'ordering': ['-aircraft_id'],
            },
        ),
    ]
