# Generated by Django 4.1.2 on 2022-10-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarik',
            name='engine_id',
            field=models.TextField(blank=True, verbose_name='engine_id'),
        ),
        migrations.AddField(
            model_name='yarik',
            name='flight_datetime',
            field=models.TextField(blank=True, verbose_name='flight_datetime'),
        ),
        migrations.AddField(
            model_name='yarik',
            name='flight_phase',
            field=models.TextField(blank=True, verbose_name='flight_phase'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='AGW',
            field=models.FloatField(blank=True, verbose_name='ACTUAL GROSS WEIGHT (LB)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='CAS',
            field=models.FloatField(blank=True, verbose_name='COMPUTED AIR SPEED (KNOTS)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='IAI',
            field=models.FloatField(blank=True, verbose_name='WING A/I'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='IAIE',
            field=models.FloatField(blank=True, verbose_name='ENG ANTI-ICE SETTING'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='IBE',
            field=models.FloatField(blank=True, verbose_name='ENG BLEED VALVE ENG 1'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='IBP',
            field=models.FloatField(blank=True, verbose_name='PACK VALVE 1'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='IHPSOV',
            field=models.FloatField(blank=True, verbose_name='PACK FLOW 1'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='IVS12',
            field=models.FloatField(blank=True, verbose_name='ISOLATION VALVE SWITCH 1-2'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='SAT',
            field=models.FloatField(blank=True, verbose_name='STATIC AIR TEMPERATURE (SAT)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZALT',
            field=models.FloatField(blank=True, verbose_name='PRESSURE ALTITUDE (FEET)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZHPTAC',
            field=models.FloatField(blank=True, verbose_name='HPT ACTIVE CLEARANCE CNTL'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZLPTAC',
            field=models.FloatField(blank=True, verbose_name='LPT ACTIVE CLEARANCE CNTL'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZPCN12',
            field=models.FloatField(blank=True, verbose_name='N1 INDICATED'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZPCN25',
            field=models.FloatField(blank=True, verbose_name='N2 (HIGH SPEED ROTOR)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZPHSF',
            field=models.FloatField(blank=True, verbose_name='PHASE ANGLE'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZPHSR',
            field=models.FloatField(blank=True, verbose_name='PHASE ANGLE (REAR)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZPN12R',
            field=models.FloatField(blank=True, verbose_name='CORRECTED N1 INPUT FROM FADEC (%RPM)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZPOIL',
            field=models.FloatField(blank=True, verbose_name='OIL PRESSURE (PSI)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZPS3',
            field=models.FloatField(blank=True, verbose_name='PS13 (FAN OGV DISCHARGE)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZT1A',
            field=models.FloatField(blank=True, verbose_name='TOTAL AIR TEMP (DEG C)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZT1AB',
            field=models.FloatField(blank=True, verbose_name="FAN INLET TOTAL TEMPERATURE FROM FADEC (DEG C)']"),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZT3',
            field=models.FloatField(blank=True, verbose_name='HPC DISCHARG TOT TEMP (DEG)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZT49',
            field=models.FloatField(blank=True, verbose_name='EGT-HPT DISCHRG TOT TMP(DEG)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZTAMB',
            field=models.FloatField(blank=True, verbose_name='STATIC AIR TEMPERATURE FROM FADEC (DEG R)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZTLA',
            field=models.FloatField(blank=True, verbose_name='THROTTLE LEVER ANGLE(DEG)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZTNAC',
            field=models.FloatField(blank=True, verbose_name='NACELLE TEMP(DEG C)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZTOIL',
            field=models.FloatField(blank=True, verbose_name='OIL TEMP (DEG C)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZVB1F',
            field=models.FloatField(blank=True, verbose_name='VIB FAN/LO SPD (FAN PICKUP)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZVB1R',
            field=models.FloatField(blank=True, verbose_name='VIB LPT/LOW SPD(REAR PICKUP)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZVB2F',
            field=models.FloatField(blank=True, verbose_name='VIB COR/HI SPD (FAN PICKUP)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZVB2R',
            field=models.FloatField(blank=True, verbose_name='VIB HPT/HI SPD (REAR PICKUP)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZVIAS',
            field=models.FloatField(blank=True, verbose_name='INDICATED_AIR_SPEED'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZVSV',
            field=models.FloatField(blank=True, verbose_name='INDICATED_AIR_SPEED'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZWBP1',
            field=models.FloatField(blank=True, verbose_name='PACK FLOW 1'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZWBP1_8E',
            field=models.FloatField(blank=True, verbose_name='CF34-8E PACK FLOW 1 - NOT USED BY BLEED ADJUSTMENT'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZWBP2',
            field=models.FloatField(blank=True, verbose_name='PACK FLOW 2'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZWBP2_8E',
            field=models.FloatField(blank=True, verbose_name='CF34-8E PACK FLOW 2 - NOT USED BY BLEED ADJUSTMENT'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZWF36',
            field=models.FloatField(blank=True, verbose_name='VAR STATOR VANES POS (VAR)'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ZXM',
            field=models.FloatField(blank=True, verbose_name='MACH'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='ac_manufacturer',
            field=models.TextField(blank=True, verbose_name='ac manufacturer'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='aircraft_family',
            field=models.TextField(blank=True, verbose_name='aircraft family'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='aircraft_grp',
            field=models.TextField(blank=True, verbose_name='aircraft grp'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='aircraft_id',
            field=models.TextField(blank=True, verbose_name='aircraft id'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='aircraft_type',
            field=models.TextField(blank=True, verbose_name='aircraft type'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='engine_family',
            field=models.TextField(blank=True, verbose_name='engine family'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='engine_position',
            field=models.IntegerField(blank=True, verbose_name='engine position'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='engine_type',
            field=models.TextField(blank=True, verbose_name='engine type'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='manufacturer',
            field=models.TextField(blank=True, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='n1_modifier',
            field=models.FloatField(blank=True, verbose_name='n1 modifier'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='number_blades',
            field=models.FloatField(blank=True, verbose_name='number blades'),
        ),
    ]
