# Generated by Django 4.1.2 on 2022-10-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphs', '0004_alter_yarik_engine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarik',
            name='engine_type',
            field=models.CharField(choices=[('CFM56-5B4', 'CFM56-5B4'), ('CF34-8E5', 'CF34-8E5'), ('CFM56-7B27/B1', 'CFM56-7B27/B1'), ('CFM56-7B26', 'CFM56-7B26'), ('CFM56-5B3', 'CFM56-5B3')], default='CFM56-5B4', max_length=15, verbose_name='engine type'),
        ),
    ]
