# Generated by Django 4.1.2 on 2022-10-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphs', '0006_alter_yarik_ac_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarik',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('CFM INTERNATIONAL', 'CFM INTERNATIONAL'), ('GE AIRCRAFT ENGINES', 'GE AIRCRAFT ENGINES')], max_length=30, null=True, verbose_name='manufacturer'),
        ),
    ]
