# Generated by Django 4.1.2 on 2022-10-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphs', '0008_alter_yarik_aircraft_grp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarik',
            name='engine_id',
            field=models.FloatField(blank=True, null=True, verbose_name='engine_id'),
        ),
    ]
