# Generated by Django 4.1.2 on 2022-10-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphs', '0009_alter_yarik_engine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarik',
            name='engine_id',
            field=models.TextField(blank=True, null=True, verbose_name='engine_id'),
        ),
    ]
