# Generated by Django 4.1.2 on 2022-10-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphs', '0010_alter_yarik_engine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarik',
            name='IAIE',
            field=models.CharField(blank=True, choices=[(0.0, 0.0), (1.0, 1.0)], max_length=10, null=True, verbose_name='ENG ANTI-ICE SETTING'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='IBE',
            field=models.CharField(blank=True, choices=[(0.0, 0.0), (1.0, 1.0)], max_length=10, null=True, verbose_name='ENG BLEED VALVE ENG 1'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='IBP',
            field=models.CharField(blank=True, choices=[(0.0, 0.0), (1.0, 1.0)], max_length=10, null=True, verbose_name='PACK VALVE 1'),
        ),
        migrations.AlterField(
            model_name='yarik',
            name='n1_modifier',
            field=models.CharField(blank=True, choices=[(0.0, 0.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (4.0, 4.0), (5.0, 5.0), (6.0, 6.0), (7.0, 7.0)], max_length=10, null=True, verbose_name='n1 modifier'),
        ),
    ]
